@host = http://localhost:8080
@codProd = 10

### Post usuario
POST {{host}}/usuario/cadastra
Content-Type: application/json

{
    "nome": "teste",
    "eMail": "teste",
    "senha": "teste"
}
###

### Post login
POST {{host}}/usuario/conecta
Content-Type: application/json

{
    "eMail": "test",
    "senha": "teste"
}
###

### Post produto
POST {{host}}/produto/cadastra
Content-Type: multipart/form-data; boundary="boundary"

--boundary
Content-Disposition: form-data; name="codUsrCr"

1
--boundary
Content-Disposition: form-data; name="nome"

produtoTeste
--boundary
Content-Disposition: form-data; name="preco"

13,99
--boundary
Content-Disposition: form-data; name="estadoUso"

novo
--boundary
Content-Disposition: form-data; name="codCla"

2
--boundary--
###

### Get produto
{{host}}/produto/dados
###

### Delete produto
DELETE {{host}}/produto/remove/?codProd={{codProd}}
###

### Patch produto
PATCH {{host}}/produto/compra/{{codProd}}            