@host = http://localhost:8080

### POST produto
POST {{host}}/data/produtos
Content-Type: application/json

{   
    "nome": "idoso chorano",
    "preço": 100,
    "imagem": "../img/idosotriste.jpeg",
    "categoria": "Objetos"
} 


### DELETE produto
DELETE {{host}}/data/produtos?id=3896da62-f04d-46c5-943c-012f21a987a8

### GET produtos
GET {{host}}/data/produtos


### POST conta
POST {{host}}/cadastro
Content-Type: application/json

{
    "nome": "luiz",
    "senha": "senha"
}


### DELETE conta
DELETE {{host}}/cadastro?id=ff849298-dbb0-483e-a6b0-4824b06866a0


### POST login
POST {{host}}/login
Content-Type: application/json

{
    "nome": "luiz",
    "senha": "senha"
}