@host = http://localhost:8080

### POST produto
POST {{host}}/data/produtos
Content-Type: application/json

{   
    "nome": "caisa de tapa",
    "preço": 100,
    "imagem": "../img/bioconstrucao_.jpg",
    "categoria": "Objetos"
} 


### DELETE produto
DELETE {{host}}/data/produtos?id=a86db833-7f75-4c4b-96ae-03a459a797b1

### GET produtos
GET {{host}}/data/produtos


### POST conta
POST {{host}}/cadastro
Content-Type: application/json

{
    "nome": "luiz",
    "senha": "senha"
}


### DELETE conta
DELETE {{host}}/cadastro?id=9551ea1d-9910-434f-9f82-25e67f883b1c


### POST login
POST {{host}}/login
Content-Type: application/json

{
    "nome": "luiz",
    "senha": "senha"
}

### GET usuarios
GET {{host}}/usuarios


### GET marcas
GET {{host}}/marcas