@host = http://localhost:8080

### POST produto
POST {{host}}/data/produtos
Content-Type: application/json

{
    "nome": "idoso triste",
    "preço": 100,
    "imagem": "../img/idosotriste.jpeg",
    "categoria": "Objetos"
} 


### DELETE produto
DELETE {{host}}/data/produtos?id=

### GET produtos
GET {{host}}/data/produtos


### POST conta
POST {{host}}/cadastro
Content-Type: application/json

{
    "nome": "artchucks",
    "senha": "123"
}


### DELETE conta
DELETE {{host}}/cadastro?id=


### POST login
POST {{host}}/login
Content-Type: application/json

{
    "nome": "art",
    "senha": "123"
}