@host = http://localhost:8080

### POST produto
POST {{host}}/data/produtos
Content-Type: application/json

{
    "nome": "idoso triste",
    "preço": 15,
    "imagem": "../img/idosotriste.jpeg",
    "categoria": "Objetos"
} 


### DELETE produto
DELETE {{host}}/data/produtos?id=9f2e77fe-8395-4536-8be0-f708be42f959

### GET produtos
GET {{host}}/data/produtos


### POST conta
POST {{host}}/cadastro
Content-Type: application/json

{
    "nome": "art",
    "senha": "123"
}


### DELETE conta
DELETE {{host}}/cadastro?id=id-conta


### POST login
POST {{host}}/login
Content-Type: application/json

{
    "nome": "art",
    "senha": "123"
}