@host = http://localhost:8080

### POST produto
POST {{host}}/cadastro/produto
Content-Type: multipart/form-data; boundary="boundary"

--boundary
Content-Disposition: form-data; name="nome"

calça jeans
--boundary
Content-Disposition: form-data; name="preco"

100.49
--boundary
Content-Disposition: form-data; name="descricao"

otima peça, linda, super ventilada
--boundary
Content-Disposition: form-data; name="estado_uso"

novo
--boundary
Content-Disposition: form-data; name="imagem"; filename="images.jpeg"
Content-Type: image/jpeg

/home/arthur/Downloads/images.jpeg
--boundary--

### DELETE produto
DELETE {{host}}/cadastro/produto?cod_pec=5
### GET produtos
GET {{host}}/data/produtos

###POST usuario
POST {{host}}/cadastro/usuario
Content-Type: application/json

{
    "nome": "Nome",
    "estado_uso": "FDSHAFLKSJ"
}

### POST conta
POST {{host}}/cadastro
Content-Type: application/json

{
    "nome": "predo",
    "senha": "senha"
}


### DELETE conta
DELETE {{host}}/cadastro?id=1


### POST login
POST {{host}}/login
Content-Type: application/json

{
    "nome": "luiz",
    "senha": "senha"
}

### GET usuarios
GET {{host}}/usuarios


### GET marcas
GET {{host}}/marcas
