@host = http://localhost:8080

### POST produto
POST {{host}}/cadastro/produto
Content-Type: multipart/form-data

{   
    "nome": "caisa de tapa",
    "preco": 100,
    "imagem": "../img/bioconstrucao_.jpg",
    "estado_uso": "nova"
} 


### DELETE produto
DELETE {{host}}/data/produtos?id=4
### GET produtos
GET {{host}}/data/produtos


### POST conta
POST {{host}}/cadastro
Content-Type: application/json

{
    "nome": "predo",
    "senha": "senha"
}


### DELETE conta
DELETE {{host}}/cadastro?id=1


### POST login
POST {{host}}/login
Content-Type: application/json

{
    "nome": "luiz",
    "senha": "senha"
}

### GET usuarios
GET {{host}}/usuarios


### GET marcas
GET {{host}}/marcas
