@host = http://localhost:8080

### POST produto
POST {{host}}/data/produtos
Content-Type: application/json

{
    "preço": 100,
    "imagem": "../img/idosotriste.jpeg",
    "categoria": "Objetos"
} 


### DELETE produto
DELETE {{host}}/data/produtos?id=19e3fcdb-c64f-44d8-b5c4-1f59f0b42ad8

### GET produtos
GET {{host}}/data/produtos


### POST conta
POST {{host}}/cadastro
Content-Type: application/json

{
    "nome": "ar",
    "senha": "123"
}


### DELETE conta
DELETE {{host}}/cadastro?id=3f5214f8-8a2d-441a-b08e-c14fe11b6e6e


### POST login
POST {{host}}/login
Content-Type: application/json

{
    "nome": "a",
    "senha": "123"
}